#!/bin/bash
apt-get update
apt-get install -y openjdk-11-jdk
apt-get install -y unzip wget curl
wget https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
tar -xvzf geckodriver-v0.27.0-linux64.tar.gz
mv geckodriver /usr/local/bin
chmod +x /usr/local/bin/gecko*
cd "$BITBUCKET_CLONE_DIR"
npm install selenium-webdriver
npm install chromedriver
npm install geckodriver
npm install mozilla
export DISPLAY=:99.0
Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
npm audit fix --force
node .test/sequence.cjs $ENVIRONMENT
node .test/credible-ft.cjs $ENVIRONMENT
