import { z } from 'zod';

export const cardResponse = {
	uuid: '',
	created_at: '',
	updated_at: '',
	token_id: '',
	code: '',
	expiry_month: '',
	expiry_year: '',
	last_4_digit: '',
	name_on_card: '',
	card_type: '',
	is_active: true,
	customer_code: '',
};

export const clientObjectResponse = {
	uuid: '',
	created_at: '',
	updated_at: '',
	country: '',
	state: '',
	address_line1: '',
	postal_code: '',
	organization: '',
	noOfStaff: '',
	is_active: true,
	is_lead_generation_job: true,
	is_lead_generation_candidate: true,
	is_background_check: true,
	app_logo: '',
	app_domain: '',
	app_title: '',
	primary_btn_bg_color: '',
	secondry_btn_bg_color: '',
	primary_btn_txt_color: '',
	secondry_btn_txt_color: '',
	brand_primary_color: '',
	brand_secondry_color: '',
	brand_tertiary_color: '',
	link_txt: '',
	white_label_enabled: true,
	is_archived: false,
	archived_at: '',
	is_bgcheck_allow_pay: false,
	is_sms_allow: true,
	last_month_invoice: false,
	invoices: null,
	customer_id: null,
	subscription_id: null,
	billing: null,
	payment_card: '',
};

export const paymentCardResponse = {
	uuid: '',
	created_at: '',
	updated_at: '',
	token_id: '',
	code: '',
	expiry_month: '',
	expiry_year: '',
	last_4_digit: '',
	name_on_card: '',
	card_type: '',
	is_active: true,
	customer_code: '',
};

export const cardSchema = z.object({
	card_number: z.string().trim(),
	expiry_month: z.string().trim(),
	expiry_year: z.string().trim(),
	cvd: z.string().trim(),
	name_on_card: z.string().trim(),
	card_type: z.string().trim(),
});

export const billingSchema = z.object({
	account_emails: z.string().email().array(),
	company_name: z.string(),
	business_number: z.string().default(''),
	street_address: z.string(),
	city: z.string(),
	zip_code: z.string(),
	state: z.string(),
	country: z.string(),
	client_id: z.string().optional(),
});

export const sampleBillingData = {
	uuid: '6e8635d1-1f00-4d6c-ae26-c451c86272d4',
	created_at: '2024-03-13T14:17:39.730090Z',
	updated_at: '2024-03-13T14:17:39.730357Z',
	account_emails: ['hasan.arshad18@gmail.com', 'mohamed@credibled.com'],
	company_name: 'Credibled',
	business_number: '32732',
	street_address: '10 Symphony Circle, Unit 2B, Buffalo, NY 14201',
	city: 'Buffalo',
	zip_code: '14201',
	state: 'New York',
	country: 'India',
};

export const sampleInvoice = {
	uuid: '',
	created_at: '',
	updated_at: '',
	invoice_id: '',
	invoice_url: '',
	invoice_pay_url: '',
	invoice_number: '',
	status: false,
	invoice_due_date: '',
	invoice_paid_on: '',
	amount: 0,
	tansaction_id: '',
	approved: '',
	payment_method: '',
	payment_process: '',
	details_csv: '',
	csv_url: '',
};
